### ISSUE TITLE
solc-remaps in slither-config does not seem to work with foundry

### ISSUE THREAD

**Issue by entire** [crytic/slither-action#11]
Slither works locally, but slither actions on GitHub Actions cannot seem to find third party libs when working w/ [Foundry](https://github.com/foundry-rs/foundry)

here is the `.slither.config.json`

```json
{
    "solc_remaps": [
        "forge-std=./contracts/lib/forge-std/src",
    ]
}
```

calling this from my root dir:
`slither contracts/src --config-file contracts/.slither.config.json` works locally

but when I run it on GitHub actions, it can't find the paths and ends in: 

here's my GitHub actions yaml
```yaml
- name: Slither
  uses: crytic/slither-action@v0.1.1
    with:
      target: "contracts/src"
      slither-config: "contracts/.slither.config.json"
```

here's the error I encounter. it seems to not be able to find the right path
```
Error: Source "forge-std/Test.sol" not found: File not found.
 --> contracts/src/SimpleContract.sol:5:1:
  |
5 | import "forge-std/Test.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Using
- foundry 0.2.0
- solc 0.8.7
- slither 0.8.3
