### ISSUE TITLE
Make action compatible with custom plugin system

### ISSUE THREAD

**Issue by 0xalpharush** [crytic/slither-action#16]
Slither has a custom plugin system and it'd be nice to have it easily integrate into the github action by registering a file(s) and including those detectors in the run. 
https://github.com/crytic/slither/tree/master/plugin_example

**Comment by elopez** [comment]
I was thinking about a way to implement this. What about a way to provide a custom requirements file, to be installed after Slither? I left an untested draft in #21 if you want to see how it would look like.

```yaml
name: Slither Analysis
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # let's say plugins are bundled in the repository or checked out @ 'plugins/'
      - uses: crytic/slither-action@dev-slither-plugins
        with:
          target: 'src/'
          slither-plugins: 'plugins/requirements.txt'
```
