### ISSUE TITLE
Disabling Foundry installation

### ISSUE THREAD

**Issue by frangio** [crytic/slither-action#44]
There is currently a problem in foundry around glibc versioning that causes installation to fail in this action, resulting in a failed run. See https://github.com/foundry-rs/foundry/issues/3827

Is there a way to skip its installation entirely? In our case we have a dual Hardhat-Foundry repository so we just need Hardhat. Neither forcing the framework to Hardhat or disabling foundry compilation seems to actually skip installation in the test that I ran.

**Comment by montyly** [comment]
I think that if you set `ignore-compile: true`, and you run the install + hardhat manually before calling `slither-action` it might work.

I haven't tested yet, but following something like the `dapp` example might work: https://github.com/crytic/slither-action#example-workflow-dapp

**Comment by thedavidmeister** [comment]
I am looking for this so that i can use the foundry action to install a specific version of foundry

as it is currently slither will override any existing foundry installation on CI

**Comment by elopez** [comment]
hey @thedavidmeister! The Slither action runs inside a container so any existing foundry installations on the github runner are unfortunately inaccesible. If you'd like to use a foundry installation on the runner itself you can pre-build the project and then run the action with `ignore-compile: true`, similarly to the [dapp example](https://github.com/crytic/slither-action#example-workflow-dapp) we have on the project readme.

(the following example is untested, but it should give you an idea of what I'm saying)
```yaml
name: Slither Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
          submodules: recursive

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Build the contracts
      run: forge build --build-info

    - name: Run Slither
      uses: crytic/slither-action@v0.3.0
      with:
        ignore-compile: true
```
