### ISSUE TITLE
Install foundry in the container

### ISSUE THREAD

**Issue by montyly** [crytic/slither-action#5]

**Comment by elopez** [comment]
Hi @EliecerC; the Slither action internally uses a Docker container to execute, so any other programs you may have installed outside of that, directly in the GH Actions worker (e.g. what the `foundry-rs/foundry-toolchain@v1` action might install) are not available in the execution context of slither.

If you want to try our PR (#8) before it is merged, you can write `uses: crytic/slither-action@dev-install-foundry` on your workflow. Something like the following should work, adapted from the workflow you posted:

```yaml
name: Slither Analysis

on: 
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run Slither
        uses: crytic/slither-action@dev-install-foundry
```

**Comment by EliecerC** [comment]
Oh! that makes a lot of sense, thank you @elopez!

**Comment by elopez** [comment]
Also, if you want to run with the stable version of the action, you can try and use `ignore-compile` in the slither action, and compile beforehand. This is the way we also support e.g. dapp

This example is untested, but _should_ work.

```yaml
name: Slither Analysis

on: 
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Build project
        run: forge build --extra-output abi --extra-output userdoc --extra-output devdoc --extra-output evm.methodIdentifiers --force

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1 
        with:
          ignore-compile: true
```
