### ISSUE TITLE
Markdown example no longer working

### ISSUE THREAD

**Issue by TheWisestOne** [crytic/slither-action#59]
The example usage of the action given  in the docs for creating a comment in PRs using Markdown does not appear to work, as of somewhat recently. Specifically, I get an error along the lines of:
```Unhandled error: SyntaxError: Invalid left-hand side expression in postfix operation```

This appears to be related to the way the value of `${{ steps.slither.outputs.stdout }}` is inserted into the code.

I belive the output of the previous step includes multiple lines, and JS does not correctly treat the whole thing as one string in this line of code:
```
const body = `${{ steps.slither.outputs.stdout }}`
```

Instead, it tries to execute some of the output from `steps.slither.outputs.stdout` as though it were JS code. Not sure if something abut the way this code ingetion works has changed recently under the hood, but I have recently started encountering this issue across multiple repositories

**Comment by elopez** [comment]
Thanks for the report @TheWisestOne! Escaping may be a problem indeed 🤔 There may be a safer way to implement this with environment variables; could you give something like this a try if you have the time?

```yaml
...
    - name: Create/update checklist as PR comment
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      env:
        REPORT: ${{ steps.slither.outputs.stdout }}
      with:
        script: |
          const script = require('.github/scripts/comment')
          const header = '# Slither report'
          const { REPORT } = process.env
          await script({ github, context, header, REPORT })
```

@tlvince hi! tagging you for visibility; I recall you originally contributed the example, have you observed this happening recently?
